services:
  securevault-apigateway:
    image: ${DOCKER_REGISTRY-}securevaultapigateway
    build:
      context: .
      dockerfile: src/gateways/SecureVault.ApiGateway/Dockerfile
    ports:
      - "5234:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - JwtSettings__Key=${JWT_KEY}
      - JwtSettings__Issuer=securevault-identity-api
      - JwtSettings__Audience=securevault-apigateway
    networks:
      - securevault-net
    depends_on:
      - securevault-identity-api
      - securevault-vault-api
      - securevault-interaction-api
      
  securevault-identity-api:
    image: ${DOCKER_REGISTRY-}securevaultidentityapi
    build:
      context: .
      dockerfile: src/services/Identity/SecureVault.Identity.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME}
      - JwtSettings__Key=${JWT_KEY}
      - JwtSettings__RefreshTokenKey=${JWT_REFRESH_KEY}
      - JwtSettings__Issuer=securevault-identity-api
      - JwtSettings__Audience=securevault-apigateway
    networks:
      - securevault-net
    depends_on:
      consul:
        condition: service_healthy  
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  securevault-vault-api:
    image: ${DOCKER_REGISTRY-}securevaultvaultapi
    build:
      context: .
      dockerfile: src/services/Vault/SecureVault.Vault.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:27017
      - MongoDbSettings__DatabaseName=${MONGO_DB_NAME}      
      - JwtSettings__Key=${JWT_KEY}
      - JwtSettings__Issuer=securevault-identity-api
      - JwtSettings__Audience=securevault-apigateway
    networks:
      - securevault-net
    depends_on:
      consul:
        condition: service_healthy  
      mongo-db:
        condition: service_healthy

  securevault-interaction-api:
    image: ${DOCKER_REGISTRY-}securevaultinteractionapi
    build:
      context: .
      dockerfile: src/services/Interaction/SecureVault.Interaction.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtSettings__Key=${JWT_KEY}
      - JwtSettings__Issuer=securevault-identity-api
      - JwtSettings__Audience=securevault-apigateway
    networks:
      - securevault-net
    depends_on:
      consul:
        condition: service_healthy  

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5433:5432"
    networks:
      - securevault-net
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27018:27017"
    networks:
      - securevault-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - securevault-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - securevault-net
    healthcheck:
      test: ["CMD", "consul", "operator", "raft", "list-peers"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_PASSWORD}
    ports:
      - "8888:80"
      - "5341:5341"
    volumes:
      - seq_data:/data
    networks:
      - securevault-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
  mongo_data:
  postgres_sync_data:
  seq_data:

networks:
  securevault-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16