<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\SecureVault.Shared.RabbitMQ\SecureVault.Shared.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\..\shared\SecureVault.Shared.Result\SecureVault.Shared.Result.csproj" />
    <ProjectReference Include="..\SecureVault.Identity.Domain\SecureVault.Identity.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\UserRecoveryDataDto\" />
  </ItemGroup>

</Project>
