<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>0b4652ff-002f-4c1a-ac4d-613a45bdc7db</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Seq" Version="9.5.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="9.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Polly" Version="8.6.3" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="Serilog.Enrichers.OpenTelemetry" Version="1.0.1" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
		<PackageReference Include="Aspire.StackExchange.Redis" Version="9.5.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\aspire\SecureVault.ServiceDefaults\SecureVault.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>
